package com.music.friends.app.dto;

import lombok.Data;

@Data
public class UserInfoDTO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   微信号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.we_chat
     *
     * @mbg.generated
     */
    private String weChat;

    /**
     * Database Column Remarks:
     *   性别 true女 false男
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     * 用户Id
    */
    private String userId;

    /**
     * 创建时间
     */
    private String createTime;
}
