package com.music.friends.app.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music_friends_idea
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Idea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_idea.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   图片路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_idea.pictures
     *
     * @mbg.generated
     */
    private String pictures;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_idea.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   1 公开 2 好友可见
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_idea.authority_flag
     *
     * @mbg.generated
     */
    private Integer authorityFlag;

    /**
     * Database Column Remarks:
     *   所属用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_idea.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_idea.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_idea.id
     *
     * @return the value of music_friends_idea.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_idea.id
     *
     * @param id the value for music_friends_idea.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_idea.pictures
     *
     * @return the value of music_friends_idea.pictures
     *
     * @mbg.generated
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_idea.pictures
     *
     * @param pictures the value for music_friends_idea.pictures
     *
     * @mbg.generated
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_idea.create_time
     *
     * @return the value of music_friends_idea.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_idea.create_time
     *
     * @param createTime the value for music_friends_idea.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_idea.authority_flag
     *
     * @return the value of music_friends_idea.authority_flag
     *
     * @mbg.generated
     */
    public Integer getAuthorityFlag() {
        return authorityFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_idea.authority_flag
     *
     * @param authorityFlag the value for music_friends_idea.authority_flag
     *
     * @mbg.generated
     */
    public void setAuthorityFlag(Integer authorityFlag) {
        this.authorityFlag = authorityFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_idea.user_id
     *
     * @return the value of music_friends_idea.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_idea.user_id
     *
     * @param userId the value for music_friends_idea.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_idea.content
     *
     * @return the value of music_friends_idea.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_idea.content
     *
     * @param content the value for music_friends_idea.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}