package com.music.friends.app.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music_friends_like
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Like {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_like.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   内容Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_like.like_id
     *
     * @mbg.generated
     */
    private String likeId;

    /**
     * Database Column Remarks:
     *   点赞者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_like.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * 被点赞者
     */
    private String likedUserId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_like.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   点赞类型 1 动态 2 歌曲 3 视频
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_like.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_like.id
     *
     * @return the value of music_friends_like.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_like.id
     *
     * @param id the value for music_friends_like.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_like.like_id
     *
     * @return the value of music_friends_like.like_id
     *
     * @mbg.generated
     */
    public String getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_like.like_id
     *
     * @param likeId the value for music_friends_like.like_id
     *
     * @mbg.generated
     */
    public void setLikeId(String likeId) {
        this.likeId = likeId == null ? null : likeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_like.user_id
     *
     * @return the value of music_friends_like.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_like.user_id
     *
     * @param userId the value for music_friends_like.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_like.create_time
     *
     * @return the value of music_friends_like.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_like.create_time
     *
     * @param createTime the value for music_friends_like.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_like.type
     *
     * @return the value of music_friends_like.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_like.type
     *
     * @param type the value for music_friends_like.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    public String getLikedUserId() {
        return likedUserId;
    }

    public void setLikedUserId(String likedUserId) {
        this.likedUserId = likedUserId;
    }
}