package com.music.friends.app.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music_friends_report
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Report {
    /**
     * Database Column Remarks:
     *   举报主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_report.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   举报的内容Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_report.report_id
     *
     * @mbg.generated
     */
    private String reportId;

    /**
     * Database Column Remarks:
     *   举报者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_report.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   举报的原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_report.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_report.id
     *
     * @return the value of music_friends_report.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_report.id
     *
     * @param id the value for music_friends_report.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_report.report_id
     *
     * @return the value of music_friends_report.report_id
     *
     * @mbg.generated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_report.report_id
     *
     * @param reportId the value for music_friends_report.report_id
     *
     * @mbg.generated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_report.user_id
     *
     * @return the value of music_friends_report.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_report.user_id
     *
     * @param userId the value for music_friends_report.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_report.create_time
     *
     * @return the value of music_friends_report.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_report.create_time
     *
     * @param createTime the value for music_friends_report.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_report.reason
     *
     * @return the value of music_friends_report.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_report.reason
     *
     * @param reason the value for music_friends_report.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}