package com.music.friends.app.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music_friends_user_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserInfo {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   微信号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.we_chat
     *
     * @mbg.generated
     */
    private String weChat;

    /**
     * Database Column Remarks:
     *   性别 true女 false男
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.id
     *
     * @return the value of music_friends_user_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.id
     *
     * @param id the value for music_friends_user_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.nick_name
     *
     * @return the value of music_friends_user_info.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.nick_name
     *
     * @param nickName the value for music_friends_user_info.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.email
     *
     * @return the value of music_friends_user_info.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.email
     *
     * @param email the value for music_friends_user_info.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.we_chat
     *
     * @return the value of music_friends_user_info.we_chat
     *
     * @mbg.generated
     */
    public String getWeChat() {
        return weChat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.we_chat
     *
     * @param weChat the value for music_friends_user_info.we_chat
     *
     * @mbg.generated
     */
    public void setWeChat(String weChat) {
        this.weChat = weChat == null ? null : weChat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.sex
     *
     * @return the value of music_friends_user_info.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.sex
     *
     * @param sex the value for music_friends_user_info.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.birthday
     *
     * @return the value of music_friends_user_info.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.birthday
     *
     * @param birthday the value for music_friends_user_info.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.age
     *
     * @return the value of music_friends_user_info.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.age
     *
     * @param age the value for music_friends_user_info.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.user_id
     *
     * @return the value of music_friends_user_info.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.user_id
     *
     * @param userId the value for music_friends_user_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.create_time
     *
     * @return the value of music_friends_user_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.create_time
     *
     * @param createTime the value for music_friends_user_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_info.update_time
     *
     * @return the value of music_friends_user_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_info.update_time
     *
     * @param updateTime the value for music_friends_user_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}