package com.music.friends.app.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music_friends_user_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserRole {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_role.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   角色主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user_role.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_role.id
     *
     * @return the value of music_friends_user_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_role.id
     *
     * @param id the value for music_friends_user_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_role.user_id
     *
     * @return the value of music_friends_user_role.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_role.user_id
     *
     * @param userId the value for music_friends_user_role.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_friends_user_role.role_id
     *
     * @return the value of music_friends_user_role.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_friends_user_role.role_id
     *
     * @param roleId the value for music_friends_user_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}