package com.music.friends.app.pojo;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music_friends_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class User{
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_friends_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * token密钥
     */
    private String tokenSecret;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    private Boolean accountNonExpired;

    private Boolean accountNonLocked;

    private Boolean credentialsNonExpired;

    private Boolean enabled;
}