package com.music.friends.app.dao;

import com.music.friends.app.pojo.Authority;

import java.util.List;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_authority
     *
     * @mbg.generated
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_authority
     *
     * @mbg.generated
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_authority
     *
     * @mbg.generated
     */
    Authority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Authority record);

    /**
     * 根据用户主键查询权限
     * @param id 用户主键
     * @return List<Authority>
     */
    List<Authority> selectByUserId(String id);
}