package com.music.friends.app.dao;

import com.music.friends.app.pojo.Idea;

import java.util.List;

public interface IdeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    int insert(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    int insertSelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    Idea selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_idea
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Idea record);

    List<Idea> selectByUserId(String userId);

    /**
     * 查询所有公开的状态，以及好友的仅限好友的状态，以及自己的仅限好友的状态
     * @param userId 用户主键
     * @return List<Idea>
     */
    List<Idea> selectAllPublicFriendsMyself(String userId);
}