package com.music.friends.app.dao;

import com.music.friends.app.pojo.Like;
import org.apache.ibatis.annotations.Param;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_like
     *
     * @mbg.generated
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_like
     *
     * @mbg.generated
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_like
     *
     * @mbg.generated
     */
    Like selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Like record);

    int count(String likeId);

    int delete(@Param("likeId") String likeId, @Param("userId") String userId);

    int countByEachOther(@Param("userId") String userId, @Param("likedUserId") String likedUserId);
}