package com.music.friends.app.dao;

import com.music.friends.app.pojo.Mv;

import java.util.List;

public interface MvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    int insert(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    int insertSelective(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    Mv selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_mv
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Mv record);

    List<Mv> selectAll(Mv mv);
}