package com.music.friends.app.dao;

import com.music.friends.app.pojo.NoticeMessage;

import java.util.List;

public interface NoticeMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    int insert(NoticeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    int insertSelective(NoticeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    NoticeMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(NoticeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_notice_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeMessage record);

    int batchInsert(List<NoticeMessage> list);

    List<NoticeMessage> selectAll(NoticeMessage noticeMessage);
}