package com.music.friends.app.dao;

import com.music.friends.app.pojo.UnConcern;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UnConcernMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_un_concern
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("me") String me, @Param("other") String other);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_un_concern
     *
     * @mbg.generated
     */
    int insert(UnConcern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_un_concern
     *
     * @mbg.generated
     */
    int insertSelective(UnConcern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_un_concern
     *
     * @mbg.generated
     */
    UnConcern selectByPrimaryKey(@Param("me") String me, @Param("other") String other);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_un_concern
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UnConcern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_friends_un_concern
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UnConcern record);

    List<UnConcern> selectAll(UnConcern unConcern);

    List<UnConcern> selectAllFans(String userId);
}